services:
  kavita:
    image: jvmilazz0/kavita:0.8.4
    container_name: kavita
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      TZ: ${TZ}
    ports:
      - ${APP_PORT}:5000
    volumes:
      - ${APP_DATA_DIR}/data/kavita-config:/kavita/config
      - ${ROOT_FOLDER_HOST}/media/data/books:/books
      - ${ROOT_FOLDER_HOST}/media/data/comics:/comics
      - ${ROOT_FOLDER_HOST}/media/data/manga:/manga
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.kavita-web-redirect.redirectscheme.scheme: https
      traefik.http.services.kavita.loadbalancer.server.port: "5000"
      traefik.http.routers.kavita-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kavita-insecure.entrypoints: web
      traefik.http.routers.kavita-insecure.service: kavita
      traefik.http.routers.kavita-insecure.middlewares: kavita-web-redirect
      traefik.http.routers.kavita.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kavita.entrypoints: websecure
      traefik.http.routers.kavita.service: kavita
      traefik.http.routers.kavita.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

