services:
  drawio:
    image: jgraph/drawio:26.0.6
    container_name: drawio
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:8080
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.drawio-web-redirect.redirectscheme.scheme: https
      traefik.http.services.drawio.loadbalancer.server.port: "8080"
      traefik.http.routers.drawio-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.drawio-insecure.entrypoints: web
      traefik.http.routers.drawio-insecure.service: drawio
      traefik.http.routers.drawio-insecure.middlewares: drawio-web-redirect
      traefik.http.routers.drawio.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.drawio.entrypoints: websecure
      traefik.http.routers.drawio.service: drawio
      traefik.http.routers.drawio.tls.certresolver: myresolver
    tty: true
    stdin_open: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

