services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.96.2
    container_name: code-server
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ}
      PASSWORD: ${CODESERVER_PASSWORD}
      SUDO_PASSWORD: ${CODESERVER_SUDO_PASSWORD}
      DEFAULT_WORKSPACE: /config/workspace
    ports:
      - ${APP_PORT}:8443
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/projects:/projects
      - ${ROOT_FOLDER_HOST}/app-data:/runtipi/app-data
      - ${ROOT_FOLDER_HOST}/user-config:/runtipi/user-config
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.code-server-web-redirect.redirectscheme.scheme: https
      traefik.http.services.code-server.loadbalancer.server.port: "8443"
      traefik.http.routers.code-server-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.code-server-insecure.entrypoints: web
      traefik.http.routers.code-server-insecure.service: code-server
      traefik.http.routers.code-server-insecure.middlewares: code-server-web-redirect
      traefik.http.routers.code-server.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.code-server.entrypoints: websecure
      traefik.http.routers.code-server.service: code-server
      traefik.http.routers.code-server.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

