services:
  joplin:
    image: florider89/joplin-server:3.0.1
    container_name: joplin
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      APP_PORT: "22300"
      APP_BASE_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}/
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${JOPLIN_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DATABASE: joplin
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: db-joplin
      MAX_TIME_DRIFT: "0"
    ports:
      - ${APP_PORT}:22300
    depends_on:
      - db-joplin
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.joplin-web-redirect.redirectscheme.scheme: https
      traefik.http.services.joplin.loadbalancer.server.port: "22300"
      traefik.http.routers.joplin-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.joplin-insecure.entrypoints: web
      traefik.http.routers.joplin-insecure.service: joplin
      traefik.http.routers.joplin-insecure.middlewares: joplin-web-redirect
      traefik.http.routers.joplin.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.joplin.entrypoints: websecure
      traefik.http.routers.joplin.service: joplin
      traefik.http.routers.joplin.tls.certresolver: myresolver
  db-joplin:
    image: postgres:14.2
    container_name: db-joplin
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      POSTGRES_PASSWORD: ${JOPLIN_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: joplin
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

