services:
  actual-budget:
    image: actualbudget/actual-server:25.2.1
    container_name: actual-budget
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:5006
    volumes:
      - ${APP_DATA_DIR}/data:/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.actual-budget-web-redirect.redirectscheme.scheme: https
      traefik.http.services.actual-budget.loadbalancer.server.port: "5006"
      traefik.http.routers.actual-budget-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.actual-budget-insecure.entrypoints: web
      traefik.http.routers.actual-budget-insecure.service: actual-budget
      traefik.http.routers.actual-budget-insecure.middlewares: actual-budget-web-redirect
      traefik.http.routers.actual-budget.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.actual-budget.entrypoints: websecure
      traefik.http.routers.actual-budget.service: actual-budget
      traefik.http.routers.actual-budget.tls.certresolver: myresolver
      traefik.http.routers.actual-budget-local-insecure.rule: Host(`actual-budget.${LOCAL_DOMAIN}`)
      traefik.http.routers.actual-budget-local-insecure.entrypoints: web
      traefik.http.routers.actual-budget-local-insecure.service: actual-budget
      traefik.http.routers.actual-budget-local-insecure.middlewares: actual-budget-web-redirect
      traefik.http.routers.actual-budget-local.rule: Host(`actual-budget.${LOCAL_DOMAIN}`)
      traefik.http.routers.actual-budget-local.entrypoints: websecure
      traefik.http.routers.actual-budget-local.service: actual-budget
      traefik.http.routers.actual-budget-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

