services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.17.5
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/spoken:/audiobooks
      - ${ROOT_FOLDER_HOST}/media/data/podcasts:/podcasts
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/metadata:/metadata
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.audiobookshelf-web-redirect.redirectscheme.scheme: https
      traefik.http.services.audiobookshelf.loadbalancer.server.port: "80"
      traefik.http.routers.audiobookshelf-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.audiobookshelf-insecure.entrypoints: web
      traefik.http.routers.audiobookshelf-insecure.service: audiobookshelf
      traefik.http.routers.audiobookshelf-insecure.middlewares: audiobookshelf-web-redirect
      traefik.http.routers.audiobookshelf.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      traefik.http.routers.audiobookshelf.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

