services:
  ollama-cpu:
    image: ollama/ollama:0.5.4
    container_name: ollama-cpu
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:11434
    volumes:
      - ${APP_DATA_DIR}/data/.ollama:/root/.ollama
    labels:
      generated: true
      traefik.enable: false
      traefik.http.middlewares.ollama-cpu-web-redirect.redirectscheme.scheme: https
      traefik.http.services.ollama-cpu.loadbalancer.server.port: "11434"
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

