services:
  firefly-iii-data-importer:
    image: fireflyiii/data-importer:version-1.5.6
    container_name: firefly-iii-data-importer
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      FIREFLY_III_URL: ${FIREFLY_III_URL}
      FIREFLY_III_ACCESS_TOKEN: ${FIREFLY_III_ACCESS_TOKEN}
      FIREFLY_III_CLIENT_ID: ${FIREFLY_III_CLIENT_ID}
      TZ: ${TZ}
      TRUSTED_PROXIES: "**"
      VERIFY_TLS_SECURITY: "false"
      APP_ENV: local
      APP_DEBUG: "false"
      LOG_CHANNEL: stack
      LOG_LEVEL: info
    ports:
      - ${APP_PORT}:8080
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.firefly-iii-data-importer-web-redirect.redirectscheme.scheme: https
      traefik.http.services.firefly-iii-data-importer.loadbalancer.server.port: "8080"
      traefik.http.routers.firefly-iii-data-importer-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.firefly-iii-data-importer-insecure.entrypoints: web
      traefik.http.routers.firefly-iii-data-importer-insecure.service: firefly-iii-data-importer
      traefik.http.routers.firefly-iii-data-importer-insecure.middlewares: firefly-iii-data-importer-web-redirect
      traefik.http.routers.firefly-iii-data-importer.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.firefly-iii-data-importer.entrypoints: websecure
      traefik.http.routers.firefly-iii-data-importer.service: firefly-iii-data-importer
      traefik.http.routers.firefly-iii-data-importer.tls.certresolver: myresolver
      traefik.http.routers.firefly-iii-data-importer-local-insecure.rule: Host(`firefly-iii-data-importer.${LOCAL_DOMAIN}`)
      traefik.http.routers.firefly-iii-data-importer-local-insecure.entrypoints: web
      traefik.http.routers.firefly-iii-data-importer-local-insecure.service: firefly-iii-data-importer
      traefik.http.routers.firefly-iii-data-importer-local-insecure.middlewares: firefly-iii-data-importer-web-redirect
      traefik.http.routers.firefly-iii-data-importer-local.rule: Host(`firefly-iii-data-importer.${LOCAL_DOMAIN}`)
      traefik.http.routers.firefly-iii-data-importer-local.entrypoints: websecure
      traefik.http.routers.firefly-iii-data-importer-local.service: firefly-iii-data-importer
      traefik.http.routers.firefly-iii-data-importer-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

