services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_PASSWORD}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data:/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.vaultwarden-web-redirect.redirectscheme.scheme: https
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
      traefik.http.routers.vaultwarden-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.vaultwarden-insecure.entrypoints: web
      traefik.http.routers.vaultwarden-insecure.service: vaultwarden
      traefik.http.routers.vaultwarden-insecure.middlewares: vaultwarden-web-redirect
      traefik.http.routers.vaultwarden.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.routers.vaultwarden.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

