version: "3.9"
services:

  wordpress_rasies:
    container_name: wordpress_rasies
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_rasies-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_rasies-db
    networks:
      - tipi_main_network
    labels:
        # Enable Traefik and set service port
        traefik.enable: true
        traefik.http.services.wordpress_rasies.loadbalancer.server.port: 80

        # Redirect HTTP to HTTPS
        traefik.http.middlewares.wordpress_rasies-redirect.redirectscheme.scheme: https

        # Web (HTTP) Router - Redirect to HTTPS
        traefik.http.routers.wordpress_rasies-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_rasies-insecure.entrypoints: web
        traefik.http.routers.wordpress_rasies-insecure.middlewares: wordpress_rasies-redirect
        traefik.http.routers.wordpress_rasies-insecure.service: wordpress_rasies

        # Websecure (HTTPS) Router - Main Router for Secure Traffic
        traefik.http.routers.wordpress_rasies.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_rasies.entrypoints: websecure
        traefik.http.routers.wordpress_rasies.tls.certresolver: myresolver
        traefik.http.routers.wordpress_rasies.service: wordpress_rasies

        # Local Domain Router (HTTP)
        traefik.http.routers.wordpress_rasies-local-insecure.rule: Host(`wordpress_rasies.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_rasies-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_rasies-local-insecure.middlewares: wordpress_rasies-redirect
        traefik.http.routers.wordpress_rasies-local-insecure.service: wordpress_rasies

        # Local Domain Router (HTTPS)
        traefik.http.routers.wordpress_rasies-local.rule: Host(`wordpress_rasies.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_rasies-local.entrypoints: websecure
        traefik.http.routers.wordpress_rasies-local.tls: true
        traefik.http.routers.wordpress_rasies-local.service: wordpress_rasies

        # Tag to indicate it's managed by runtipi
        runtipi.managed: true

  wordpress_rasies-db:
    container_name: wordpress_rasies-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true

