services:
  anse:
    image: ddiu8081/anse:v1.1.11
    container_name: anse
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PORT: "8014"
      BASE_URL: http://192.168.1.12:8111
      API_KEY: Mycobacteri@98
    ports:
      - ${APP_PORT}:8014
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.anse-web-redirect.redirectscheme.scheme: https
      traefik.http.services.anse.loadbalancer.server.port: "8014"
      traefik.http.routers.anse-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.anse-insecure.entrypoints: web
      traefik.http.routers.anse-insecure.service: anse
      traefik.http.routers.anse-insecure.middlewares: anse-web-redirect
      traefik.http.routers.anse.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.anse.entrypoints: websecure
      traefik.http.routers.anse.service: anse
      traefik.http.routers.anse.tls.certresolver: myresolver
      traefik.http.routers.anse-local-insecure.rule: Host(`anse.${LOCAL_DOMAIN}`)
      traefik.http.routers.anse-local-insecure.entrypoints: web
      traefik.http.routers.anse-local-insecure.service: anse
      traefik.http.routers.anse-local-insecure.middlewares: anse-web-redirect
      traefik.http.routers.anse-local.rule: Host(`anse.${LOCAL_DOMAIN}`)
      traefik.http.routers.anse-local.entrypoints: websecure
      traefik.http.routers.anse-local.service: anse
      traefik.http.routers.anse-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

