services:
  dashdot:
    image: mauricenino/dashdot:5.9.0
    container_name: dashdot
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      DASHDOT_SHOW_HOST: "false"
      DASHDOT_SHOW_DASH_VERSION: "true"
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_USE_IMPERIAL: "true"
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: "true"
      DASHDOT_PAGE_TITLE: dashdot
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
    ports:
      - ${APP_PORT}:3001
    volumes:
      - /:/mnt/host:ro
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.dashdot-web-redirect.redirectscheme.scheme: https
      traefik.http.services.dashdot.loadbalancer.server.port: "3001"
      traefik.http.routers.dashdot-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dashdot-insecure.entrypoints: web
      traefik.http.routers.dashdot-insecure.service: dashdot
      traefik.http.routers.dashdot-insecure.middlewares: dashdot-web-redirect
      traefik.http.routers.dashdot.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dashdot.entrypoints: websecure
      traefik.http.routers.dashdot.service: dashdot
      traefik.http.routers.dashdot.tls.certresolver: myresolver
    privileged: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

