services:
  flowise:
    image: flowiseai/flowise:2.2.5
    container_name: flowise
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PORT: "8009"
      FLOWISE_USERNAME: ${FLOWISE_USERNAME}
      FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}
      FLOWISE_SECRETKEY_OVERWRITE: ${FLOWISE_SECRETKEY_OVERWRITE}
      LANGCHAIN_ENDPOINT: ${LANGCHAIN_ENDPOINT}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      DISABLE_FLOWISE_TELEMETRY: ${DISABLE_FLOWISE_TELEMETRY}
      DATABASE_PATH: /root/.flowise
      APIKEY_PATH: /root/.flowise
      SECRETKEY_PATH: /root/.flowise
      LOG_PATH: /root/.flowise/logs
    ports:
      - ${APP_PORT}:8009
    volumes:
      - ${APP_DATA_DIR}/data/flowise:/root/.flowise
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.flowise-web-redirect.redirectscheme.scheme: https
      traefik.http.services.flowise.loadbalancer.server.port: "8009"
      traefik.http.routers.flowise-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.flowise-insecure.entrypoints: web
      traefik.http.routers.flowise-insecure.service: flowise
      traefik.http.routers.flowise-insecure.middlewares: flowise-web-redirect
      traefik.http.routers.flowise.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.flowise.entrypoints: websecure
      traefik.http.routers.flowise.service: flowise
      traefik.http.routers.flowise.tls.certresolver: myresolver
    entrypoint: /bin/sh -c "sleep 3; flowise start"
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

