services:
  planning-poker:
    image: axeleroy/self-host-planning-poker:1.2.1
    container_name: planning-poker
    restart: unless-stopped
    networks:
      - tipi_main_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.planning-poker-web-redirect.redirectscheme.scheme: https
      traefik.http.services.planning-poker.loadbalancer.server.port: "8000"
      traefik.http.routers.planning-poker-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.planning-poker-insecure.entrypoints: web
      traefik.http.routers.planning-poker-insecure.service: planning-poker
      traefik.http.routers.planning-poker-insecure.middlewares: planning-poker-web-redirect
      traefik.http.routers.planning-poker.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.planning-poker.entrypoints: websecure
      traefik.http.routers.planning-poker.service: planning-poker
      traefik.http.routers.planning-poker.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

