services:
  chatgpt-ui:
    image: wongsaang/chatgpt-ui-client:v2.5.9
    container_name: chatgpt-ui
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      SERVER_DOMAIN: http://chatgpt-ui-web-server
      DEFAULT_LOCALE: en
    ports:
      - ${APP_PORT}:80
    depends_on:
      - chatgpt-ui-web-server
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.chatgpt-ui-web-redirect.redirectscheme.scheme: https
      traefik.http.services.chatgpt-ui.loadbalancer.server.port: "80"
      traefik.http.routers.chatgpt-ui-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.chatgpt-ui-insecure.entrypoints: web
      traefik.http.routers.chatgpt-ui-insecure.service: chatgpt-ui
      traefik.http.routers.chatgpt-ui-insecure.middlewares: chatgpt-ui-web-redirect
      traefik.http.routers.chatgpt-ui.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.chatgpt-ui.entrypoints: websecure
      traefik.http.routers.chatgpt-ui.service: chatgpt-ui
      traefik.http.routers.chatgpt-ui.tls.certresolver: myresolver
  chatgpt-ui-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:v2.5.2
    container_name: chatgpt-ui-wsgi-server
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      APP_DOMAIN: ${INTERNAL_IP}:8201
      SERVER_WORKERS: "3"
      WORKER_TIMEOUT: "180"
      DB_URL: mysql://tipi:${CHATGPT_UI_DB_PASSWORD}@chatgpt-ui-db:3306/chatgptdb
      DJANGO_SUPERUSER_USERNAME: ${CHATGPT_UI_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${CHATGPT_UI_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${CHATGPT_UI_SUPERUSER_EMAIL}
      ACCOUNT_EMAIL_VERIFICATION: none
    depends_on:
      - chatgpt-ui-db
  chatgpt-ui-web-server:
    image: wongsaang/chatgpt-ui-web-server:v2.5.2
    container_name: chatgpt-ui-web-server
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      BACKEND_URL: http://chatgpt-ui-wsgi-server:8000
    ports:
      - 8201:80
    depends_on:
      - chatgpt-ui-wsgi-server
      - chatgpt-ui-db
  chatgpt-ui-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: chatgpt-ui-db
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      MYSQL_ROOT_PASSWORD: ${CHATGPT_UI_DB_PASSWORD}
      MYSQL_DATABASE: chatgptdb
      MYSQL_USER: tipi
      MYSQL_PASSWORD: ${CHATGPT_UI_DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql/config:/config
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

