services:
  beszel-agent:
    image: henrygd/beszel-agent:0.9.0
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      KEY: ${BESZEL_AGENT_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      generated: true
      traefik.enable: false
      traefik.http.middlewares.beszel-agent-web-redirect.redirectscheme.scheme: https
      traefik.http.services.beszel-agent.loadbalancer.server.port: "45876"
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

