services:
  grav:
    image: lscr.io/linuxserver/grav:1.7.48
    container_name: grav
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/grav-comfig:/config
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.grav-web-redirect.redirectscheme.scheme: https
      traefik.http.services.grav.loadbalancer.server.port: "80"
      traefik.http.routers.grav-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grav-insecure.entrypoints: web
      traefik.http.routers.grav-insecure.service: grav
      traefik.http.routers.grav-insecure.middlewares: grav-web-redirect
      traefik.http.routers.grav.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grav.entrypoints: websecure
      traefik.http.routers.grav.service: grav
      traefik.http.routers.grav.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

