services:
  obsidian-livesync:
    image: couchdb:3.1.2
    container_name: obsidian-livesync
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      COUCHDB_USER: ${OBSIDIAN_LIVESYNC_USER}
      COUCHDB_PASSWORD: ${OBSIDIAN_LIVESYNC_PASSWORD}
    ports:
      - ${APP_PORT}:5984
    volumes:
      - ${APP_DATA_DIR}/data/couchdb:/opt/couchdb/data
      - ${APP_DATA_DIR}/data/local.ini:/opt/couchdb/etc/local.ini
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.obsidian-livesync-web-redirect.redirectscheme.scheme: https
      traefik.http.services.obsidian-livesync.loadbalancer.server.port: "5984"
      traefik.http.routers.obsidian-livesync-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.obsidian-livesync-insecure.entrypoints: web
      traefik.http.routers.obsidian-livesync-insecure.service: obsidian-livesync
      traefik.http.routers.obsidian-livesync-insecure.middlewares: obsidian-livesync-web-redirect
      traefik.http.routers.obsidian-livesync.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.obsidian-livesync.entrypoints: websecure
      traefik.http.routers.obsidian-livesync.service: obsidian-livesync
      traefik.http.routers.obsidian-livesync.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

