services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:0.38.0
    container_name: stirling-pdf
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      DOCKER_ENABLE_SECURITY: ${STIRLING_PDF_DOCKER_ENABLE_SECURITY-false}
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - ${APP_DATA_DIR}/data/extraConfigs:/configs
      - ${APP_DATA_DIR}/data/customFiles:/customFiles/
      - ${APP_DATA_DIR}/data/logs:/logs/
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.stirling-pdf-web-redirect.redirectscheme.scheme: https
      traefik.http.services.stirling-pdf.loadbalancer.server.port: "8080"
      traefik.http.routers.stirling-pdf-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stirling-pdf-insecure.entrypoints: web
      traefik.http.routers.stirling-pdf-insecure.service: stirling-pdf
      traefik.http.routers.stirling-pdf-insecure.middlewares: stirling-pdf-web-redirect
      traefik.http.routers.stirling-pdf.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stirling-pdf.entrypoints: websecure
      traefik.http.routers.stirling-pdf.service: stirling-pdf
      traefik.http.routers.stirling-pdf.tls.certresolver: myresolver
    privileged: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

