services:
  nextgba:
    image: ghcr.io/meienberger/nextgba:v0.1.0
    container_name: nextgba
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      NODE_ENV: production
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/games:/data/games
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.nextgba-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nextgba.loadbalancer.server.port: "3000"
      traefik.http.routers.nextgba-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextgba-insecure.entrypoints: web
      traefik.http.routers.nextgba-insecure.service: nextgba
      traefik.http.routers.nextgba-insecure.middlewares: nextgba-web-redirect
      traefik.http.routers.nextgba.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextgba.entrypoints: websecure
      traefik.http.routers.nextgba.service: nextgba
      traefik.http.routers.nextgba.tls.certresolver: myresolver
      traefik.http.routers.nextgba-local-insecure.rule: Host(`nextgba.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextgba-local-insecure.entrypoints: web
      traefik.http.routers.nextgba-local-insecure.service: nextgba
      traefik.http.routers.nextgba-local-insecure.middlewares: nextgba-web-redirect
      traefik.http.routers.nextgba-local.rule: Host(`nextgba.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextgba-local.entrypoints: websecure
      traefik.http.routers.nextgba-local.service: nextgba
      traefik.http.routers.nextgba-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

