version: "3.9"
services:

  wordpress_aidanras:
    container_name: wordpress_aidanras
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_aidanras-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=${APP_DOMAIN}  # Ensure domain is set
      - SERVER_NAME=${APP_DOMAIN}  # Set Apache ServerName
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_aidanras-db
    networks:
      - tipi_main_network
    labels:
        # Enable Traefik and set service port
        traefik.enable: true
        traefik.http.services.wordpress_aidanras.loadbalancer.server.port: 80

        # Redirect HTTP to HTTPS
        traefik.http.middlewares.wordpress_aidanras-redirect.redirectscheme.scheme: https

        # Web (HTTP) Router - Redirect to HTTPS
        traefik.http.routers.wordpress_aidanras-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-insecure.entrypoints: web
        traefik.http.routers.wordpress_aidanras-insecure.middlewares: wordpress_aidanras-redirect
        traefik.http.routers.wordpress_aidanras-insecure.service: wordpress_aidanras

        # Websecure (HTTPS) Router - Main Router for Secure Traffic
        traefik.http.routers.wordpress_aidanras.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras.entrypoints: websecure
        traefik.http.routers.wordpress_aidanras.tls.certresolver: myresolver
        traefik.http.routers.wordpress_aidanras.service: wordpress_aidanras

        # Local Domain Router (HTTP)
        traefik.http.routers.wordpress_aidanras-local-insecure.rule: Host(`wordpress_aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_aidanras-local-insecure.middlewares: wordpress_aidanras-redirect
        traefik.http.routers.wordpress_aidanras-local-insecure.service: wordpress_aidanras

        # Local Domain Router (HTTPS)
        traefik.http.routers.wordpress_aidanras-local.rule: Host(`wordpress_aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-local.entrypoints: websecure
        traefik.http.routers.wordpress_aidanras-local.tls: true
        traefik.http.routers.wordpress_aidanras-local.service: wordpress_aidanras

        # Tag to indicate it's managed by runtipi
        runtipi.managed: true

  wordpress_aidanras-db:
    container_name: wordpress_aidanras-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true

