services:
  viewtube:
    image: mauriceo/viewtube:0.17.0
    container_name: viewtube
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      VIEWTUBE_DATABASE_HOST: viewtube-mongodb
      VIEWTUBE_REDIS_HOST: viewtube-redis
      VIEWTUBE_SECURE: "true"
      VIEWTUBE_CORS_ORIGIN: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
    ports:
      - ${APP_PORT}:8066
    volumes:
      - ${APP_DATA_DIR}/data/viewtube:/data
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.viewtube-web-redirect.redirectscheme.scheme: https
      traefik.http.services.viewtube.loadbalancer.server.port: "8066"
      traefik.http.routers.viewtube-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.viewtube-insecure.entrypoints: web
      traefik.http.routers.viewtube-insecure.service: viewtube
      traefik.http.routers.viewtube-insecure.middlewares: viewtube-web-redirect
      traefik.http.routers.viewtube.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.viewtube.entrypoints: websecure
      traefik.http.routers.viewtube.service: viewtube
      traefik.http.routers.viewtube.tls.certresolver: myresolver
  viewtube-mongodb:
    image: mongo:5
    container_name: viewtube-mongodb
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/db:/data/db
  viewtube-redis:
    image: redis:7
    container_name: viewtube-redis
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

