services:
  notemark:
    image: ghcr.io/enchant97/note-mark-frontend:0.14.1
    container_name: notemark
    restart: unless-stopped
    networks:
      - tipi_main_network
  notemark-backend:
    image: ghcr.io/enchant97/note-mark-backend:0.14.1
    container_name: notemark-backend
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      JWT_SECRET: ${NOTEMARK_SERVICE_SECRET}
      CORS_ORIGINS: "*"
    volumes:
      - ${APP_DATA_DIR}/data:/data
  notemark-proxy:
    image: ghcr.io/enchant97/note-mark-frontend:0.15.0
    container_name: notemark-proxy
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.notemark-proxy-web-redirect.redirectscheme.scheme: https
      traefik.http.services.notemark-proxy.loadbalancer.server.port: "80"
      traefik.http.routers.notemark-proxy-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.notemark-proxy-insecure.entrypoints: web
      traefik.http.routers.notemark-proxy-insecure.service: notemark-proxy
      traefik.http.routers.notemark-proxy-insecure.middlewares: notemark-proxy-web-redirect
      traefik.http.routers.notemark-proxy.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.notemark-proxy.entrypoints: websecure
      traefik.http.routers.notemark-proxy.service: notemark-proxy
      traefik.http.routers.notemark-proxy.tls.certresolver: myresolver
      traefik.http.routers.notemark-proxy-local-insecure.rule: Host(`notemark-proxy.${LOCAL_DOMAIN}`)
      traefik.http.routers.notemark-proxy-local-insecure.entrypoints: web
      traefik.http.routers.notemark-proxy-local-insecure.service: notemark-proxy
      traefik.http.routers.notemark-proxy-local-insecure.middlewares: notemark-proxy-web-redirect
      traefik.http.routers.notemark-proxy-local.rule: Host(`notemark-proxy.${LOCAL_DOMAIN}`)
      traefik.http.routers.notemark-proxy-local.entrypoints: websecure
      traefik.http.routers.notemark-proxy-local.service: notemark-proxy
      traefik.http.routers.notemark-proxy-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

