services:
  cheshire-cat-ai:
    image: ghcr.io/cheshire-cat-ai/core:1.8.0
    container_name: cheshire-cat-ai
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PYTHONUNBUFFERED: "1"
      WATCHFILES_FORCE_POLLING: "true"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/static:/app/cat/static
      - ${APP_DATA_DIR}/data/plugins:/app/cat/plugins
      - ${APP_DATA_DIR}/data/data:/app/cat/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.cheshire-cat-ai-web-redirect.redirectscheme.scheme: https
      traefik.http.services.cheshire-cat-ai.loadbalancer.server.port: "80"
      traefik.http.routers.cheshire-cat-ai-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cheshire-cat-ai-insecure.entrypoints: web
      traefik.http.routers.cheshire-cat-ai-insecure.service: cheshire-cat-ai
      traefik.http.routers.cheshire-cat-ai-insecure.middlewares: cheshire-cat-ai-web-redirect
      traefik.http.routers.cheshire-cat-ai.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cheshire-cat-ai.entrypoints: websecure
      traefik.http.routers.cheshire-cat-ai.service: cheshire-cat-ai
      traefik.http.routers.cheshire-cat-ai.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

