services:
  chatpad:
    image: ghcr.io/deiucanta/chatpad:latest
    container_name: chatpad
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:80
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.chatpad-web-redirect.redirectscheme.scheme: https
      traefik.http.services.chatpad.loadbalancer.server.port: "80"
      traefik.http.routers.chatpad-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.chatpad-insecure.entrypoints: web
      traefik.http.routers.chatpad-insecure.service: chatpad
      traefik.http.routers.chatpad-insecure.middlewares: chatpad-web-redirect
      traefik.http.routers.chatpad.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.chatpad.entrypoints: websecure
      traefik.http.routers.chatpad.service: chatpad
      traefik.http.routers.chatpad.tls.certresolver: myresolver
      traefik.http.routers.chatpad-local-insecure.rule: Host(`chatpad.${LOCAL_DOMAIN}`)
      traefik.http.routers.chatpad-local-insecure.entrypoints: web
      traefik.http.routers.chatpad-local-insecure.service: chatpad
      traefik.http.routers.chatpad-local-insecure.middlewares: chatpad-web-redirect
      traefik.http.routers.chatpad-local.rule: Host(`chatpad.${LOCAL_DOMAIN}`)
      traefik.http.routers.chatpad-local.entrypoints: websecure
      traefik.http.routers.chatpad-local.service: chatpad
      traefik.http.routers.chatpad-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

