services:
  archivebox:
    image: archivebox/archivebox:0.7.3
    command: server --quick-init 0.0.0.0:8015
    container_name: archivebox
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PORT: "8015"
      PUBLIC_INDEX: ${ARCHIVEBOX_PUBLIC_INDEX-true}
      PUBLIC_SNAPSHOTS: ${ARCHIVEBOX_PUBLIC_SNAPSHOTS-true}
      PUBLIC_ADD_VIEW: ${ARCHIVEBOX_PUBLIC_ADD_VIEW-false}
      ADMIN_USERNAME: ${ARCHIVEBOX_USERNAME}
      ADMIN_PASSWORD: ${ARCHIVEBOX_PASSWORD}
      PUID: "1000"
      PGID: "1000"
      SEARCH_BACKEND_ENGINE: ${ARCHIVEBOX_SEARCH_BACKEND_ENGINE}
      SEARCH_BACKEND_HOST_NAME: ${ARCHIVEBOX_SEARCH_BACKEND_HOST_NAME}
      SEARCH_BACKEND_PASSWORD: ${ARCHIVEBOX_SEARCH_BACKEND_PASSWORD}
      MEDIA_MAX_SIZE: ${ARCHIVEBOX_MEDIA_MAX_SIZE-750m}
      TIMEOUT: ${ARCHIVEBOX_TIMEOUT-60}
      CHECK_SSL_VALIDITY: ${ARCHIVEBOX_CHECK_SSL_VALIDITY-true}
      SAVE_ARCHIVE_DOT_ORG: ${ARCHIVEBOX_SAVE_ARCHIVE_DOT_ORGE-true}
    ports:
      - ${APP_PORT}:8015
    volumes:
      - ${APP_DATA_DIR}/data:/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.archivebox-web-redirect.redirectscheme.scheme: https
      traefik.http.services.archivebox.loadbalancer.server.port: "8015"
      traefik.http.routers.archivebox-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.archivebox-insecure.entrypoints: web
      traefik.http.routers.archivebox-insecure.service: archivebox
      traefik.http.routers.archivebox-insecure.middlewares: archivebox-web-redirect
      traefik.http.routers.archivebox.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.archivebox.entrypoints: websecure
      traefik.http.routers.archivebox.service: archivebox
      traefik.http.routers.archivebox.tls.certresolver: myresolver
      traefik.http.routers.archivebox-local-insecure.rule: Host(`archivebox.${LOCAL_DOMAIN}`)
      traefik.http.routers.archivebox-local-insecure.entrypoints: web
      traefik.http.routers.archivebox-local-insecure.service: archivebox
      traefik.http.routers.archivebox-local-insecure.middlewares: archivebox-web-redirect
      traefik.http.routers.archivebox-local.rule: Host(`archivebox.${LOCAL_DOMAIN}`)
      traefik.http.routers.archivebox-local.entrypoints: websecure
      traefik.http.routers.archivebox-local.service: archivebox
      traefik.http.routers.archivebox-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

