services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:80
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.excalidraw-web-redirect.redirectscheme.scheme: https
      traefik.http.services.excalidraw.loadbalancer.server.port: "80"
      traefik.http.routers.excalidraw-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.excalidraw-insecure.entrypoints: web
      traefik.http.routers.excalidraw-insecure.service: excalidraw
      traefik.http.routers.excalidraw-insecure.middlewares: excalidraw-web-redirect
      traefik.http.routers.excalidraw.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.excalidraw.entrypoints: websecure
      traefik.http.routers.excalidraw.service: excalidraw
      traefik.http.routers.excalidraw.tls.certresolver: myresolver
      traefik.http.routers.excalidraw-local-insecure.rule: Host(`excalidraw.${LOCAL_DOMAIN}`)
      traefik.http.routers.excalidraw-local-insecure.entrypoints: web
      traefik.http.routers.excalidraw-local-insecure.service: excalidraw
      traefik.http.routers.excalidraw-local-insecure.middlewares: excalidraw-web-redirect
      traefik.http.routers.excalidraw-local.rule: Host(`excalidraw.${LOCAL_DOMAIN}`)
      traefik.http.routers.excalidraw-local.entrypoints: websecure
      traefik.http.routers.excalidraw-local.service: excalidraw
      traefik.http.routers.excalidraw-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

