services:
  firefly-iii:
    image: fireflyiii/core:version-6.1.21
    container_name: firefly-iii
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      APP_ENV: local
      APP_DEBUG: "false"
      SITE_OWNER: ${EMAIL}
      APP_KEY: ${APP_KEY}
      STATIC_CRON_TOKEN: ${STATIC_CRON_TOKEN}
      TZ: ${TZ}
      TRUSTED_PROXIES: "**"
      DB_CONNECTION: mysql
      DB_HOST: firefly-iii-db
      DB_PORT: "3306"
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: ${MYSQL_PASSWORD}
      COOKIE_PATH: '"/"'
      COOKIE_DOMAIN: ""
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      APP_NAME: FireflyIII
      BROADCAST_DRIVER: log
      QUEUE_DRIVER: sync
      CACHE_PREFIX: firefly
      IS_HEROKU: "false"
      FIREFLY_III_LAYOUT: v1
      APP_URL: http://localhost:${APP_PORT}
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/uplodad:/var/www/html/storage/upload
    depends_on:
      - firefly-iii-db
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.firefly-iii-web-redirect.redirectscheme.scheme: https
      traefik.http.services.firefly-iii.loadbalancer.server.port: "8080"
      traefik.http.routers.firefly-iii-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.firefly-iii-insecure.entrypoints: web
      traefik.http.routers.firefly-iii-insecure.service: firefly-iii
      traefik.http.routers.firefly-iii-insecure.middlewares: firefly-iii-web-redirect
      traefik.http.routers.firefly-iii.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.firefly-iii.entrypoints: websecure
      traefik.http.routers.firefly-iii.service: firefly-iii
      traefik.http.routers.firefly-iii.tls.certresolver: myresolver
  firefly-iii-db:
    image: mariadb
    container_name: firefly-iii-db
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: firefly
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: firefly
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    hostname: fireflyiii-db
  firefly-iii-cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO-
      http://${APP_DOMAIN}/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - &&
      crond -f -L /dev/stdout"
    container_name: firefly-iii-cron
    restart: unless-stopped
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

