services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:1.9.2
    container_name: emulatorjs
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      TZ: ${TZ}
    ports:
      - 8165:3000
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/emulatorjs-config:/config
      - ${APP_DATA_DIR}/data/emulatorjs:/data
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.emulatorjs-web-redirect.redirectscheme.scheme: https
      traefik.http.services.emulatorjs.loadbalancer.server.port: "80"
      traefik.http.routers.emulatorjs-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emulatorjs-insecure.entrypoints: web
      traefik.http.routers.emulatorjs-insecure.service: emulatorjs
      traefik.http.routers.emulatorjs-insecure.middlewares: emulatorjs-web-redirect
      traefik.http.routers.emulatorjs.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emulatorjs.entrypoints: websecure
      traefik.http.routers.emulatorjs.service: emulatorjs
      traefik.http.routers.emulatorjs.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

