services:
  glance:
    image: glanceapp/glance:v0.6.3
    container_name: glance
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/glance.yml:/app/glance.yml
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.glance-web-redirect.redirectscheme.scheme: https
      traefik.http.services.glance.loadbalancer.server.port: "8080"
      traefik.http.routers.glance-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.glance-insecure.entrypoints: web
      traefik.http.routers.glance-insecure.service: glance
      traefik.http.routers.glance-insecure.middlewares: glance-web-redirect
      traefik.http.routers.glance.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.glance.entrypoints: websecure
      traefik.http.routers.glance.service: glance
      traefik.http.routers.glance.tls.certresolver: myresolver
      traefik.http.routers.glance-local-insecure.rule: Host(`glance.${LOCAL_DOMAIN}`)
      traefik.http.routers.glance-local-insecure.entrypoints: web
      traefik.http.routers.glance-local-insecure.service: glance
      traefik.http.routers.glance-local-insecure.middlewares: glance-web-redirect
      traefik.http.routers.glance-local.rule: Host(`glance.${LOCAL_DOMAIN}`)
      traefik.http.routers.glance-local.entrypoints: websecure
      traefik.http.routers.glance-local.service: glance
      traefik.http.routers.glance-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

