services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      BIND_ADDRESS: 0.0.0.0:8080
      BASE_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}/
      SEARXNG_SECRET: ${SEARXNG_SECRET_KEY}
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data:/etc/searxng
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.searxng-web-redirect.redirectscheme.scheme: https
      traefik.http.services.searxng.loadbalancer.server.port: "8080"
      traefik.http.routers.searxng-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.searxng-insecure.entrypoints: web
      traefik.http.routers.searxng-insecure.service: searxng
      traefik.http.routers.searxng-insecure.middlewares: searxng-web-redirect
      traefik.http.routers.searxng.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.searxng.entrypoints: websecure
      traefik.http.routers.searxng.service: searxng
      traefik.http.routers.searxng.tls.certresolver: myresolver
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

