services:
  mongo:
    image: mongo:7.0.2
    container_name: mongo
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${APP_PORT}:27017
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.mongo-web-redirect.redirectscheme.scheme: https
      traefik.http.services.mongo.loadbalancer.server.port: "27017"
      traefik.http.routers.mongo-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mongo-insecure.entrypoints: web
      traefik.http.routers.mongo-insecure.service: mongo
      traefik.http.routers.mongo-insecure.middlewares: mongo-web-redirect
      traefik.http.routers.mongo.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mongo.entrypoints: websecure
      traefik.http.routers.mongo.service: mongo
      traefik.http.routers.mongo.tls.certresolver: myresolver
      traefik.http.routers.mongo-local-insecure.rule: Host(`mongo.${LOCAL_DOMAIN}`)
      traefik.http.routers.mongo-local-insecure.entrypoints: web
      traefik.http.routers.mongo-local-insecure.service: mongo
      traefik.http.routers.mongo-local-insecure.middlewares: mongo-web-redirect
      traefik.http.routers.mongo-local.rule: Host(`mongo.${LOCAL_DOMAIN}`)
      traefik.http.routers.mongo-local.entrypoints: websecure
      traefik.http.routers.mongo-local.service: mongo
      traefik.http.routers.mongo-local.tls: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

